In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("archive/emails.csv")

In [12]:
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [13]:
df.shape

(5172, 3002)

In [14]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [15]:
df.tail()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5 rows x 3002 columns]

In [16]:
df.drop('Email No.', axis=1, inplace=True)

In [17]:
X = df.drop('Prediction', axis=1)
y = df['Prediction']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

K Nearest Neighbour

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
model1 = KNeighborsClassifier(n_neighbors=3)

In [23]:
model1.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [24]:
y_pred = model1.predict(X_test)

In [25]:
y_pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [29]:
target_names = ['Not Spam', 'Spam']

In [30]:
from sklearn.metrics import classification_report

In [32]:
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

    Not Spam       0.92      0.88      0.90      1097
        Spam       0.74      0.82      0.78       455

    accuracy                           0.86      1552
   macro avg       0.83      0.85      0.84      1552
weighted avg       0.87      0.86      0.86      1552



Confusion Matrix

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test,y_pred)

array([[966, 131],
       [ 83, 372]], dtype=int64)

Now let's try with 5 Neighbours

In [35]:
model2 = KNeighborsClassifier(n_neighbors=5)

In [36]:
model2.fit(X_train, y_train)

KNeighborsClassifier()

In [37]:
y_pred_2 = model2.predict(X_test)

In [38]:
y_pred_2

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [39]:
print(classification_report(y_test, y_pred_2, target_names=target_names))

              precision    recall  f1-score   support

    Not Spam       0.93      0.87      0.90      1097
        Spam       0.73      0.83      0.78       455

    accuracy                           0.86      1552
   macro avg       0.83      0.85      0.84      1552
weighted avg       0.87      0.86      0.86      1552



In [40]:
confusion_matrix(y_test,y_pred_2)

array([[958, 139],
       [ 77, 378]], dtype=int64)

Support Vector Machine \n
Kernel = Linear

In [41]:
from sklearn import svm

In [42]:
clf = svm.SVC(kernel = 'linear')

In [43]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [44]:
y_pred_3 = clf.predict(X_test)

In [45]:
y_pred_3

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [46]:
print(classification_report(y_test, y_pred_3, target_names=target_names))

              precision    recall  f1-score   support

    Not Spam       0.97      0.97      0.97      1097
        Spam       0.92      0.93      0.93       455

    accuracy                           0.96      1552
   macro avg       0.95      0.95      0.95      1552
weighted avg       0.96      0.96      0.96      1552



In [47]:
confusion_matrix(y_test, y_pred_3)

array([[1062,   35],
       [  32,  423]], dtype=int64)

Kernel = rbf

In [48]:
clf_rbf = svm.SVC(kernel='rbf')

In [49]:
clf_rbf.fit(X_train, y_train)

SVC()

In [50]:
y_pred_4 = clf_rbf.predict(X_test)

In [51]:
y_pred_4

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [52]:
print(classification_report(y_test, y_pred_4, target_names=target_names))

              precision    recall  f1-score   support

    Not Spam       0.79      0.99      0.88      1097
        Spam       0.92      0.36      0.52       455

    accuracy                           0.80      1552
   macro avg       0.85      0.67      0.70      1552
weighted avg       0.83      0.80      0.77      1552



In [53]:
confusion_matrix(y_test, y_pred_4)

array([[1082,   15],
       [ 290,  165]], dtype=int64)